package chat.shared.transferObjects;

public enum RequestType {
    LOGIN,
    SUCCESSFUL_LOGIN,
    EXISTING_USERNAME,
    UPDATE_ACTIVE_USERS,
    GET_ACTIVE_USERS,
    SEND_PUBLIC,
    RECEIVE_PUBLIC,
    AVATAR_IMAGES,
    NEXT_AVATAR_IMAGE,
    PREVIOUS_AVATAR_IMAGE,
    UPDATE_AVATAR_IMAGE,
    DISCONNECT
}
